ConfigUrl = ""

[Http]
  CORES = "*"
  Port = 80
  Path = "/"
  MaxBufferSize = 10485760
  JwtSecret = ""
  AutoAuth = false

[[Redis]]
  Name = "redis_server_demo"
  Username = "doptime"
  Password = "yourpasswordhere"
  Host = "drangonflydb.local"
  Port = 6379
  DB = 0

[[HttpRPC]]
  Name = "doptime"
  UrlBase = "https://api.doptime.com"
  Jwt = ""

[Settings]
  LogLevel = 1
