ConfigUrl = ""

[[REDIS]]
Name = "default"
Username = ""
Password = "deaf@0829"
Host = "keydb.lan"
Port = 6379
DB = 0

[JWT]
Secret = ""
Fields = "*"

[HTTP]
CORES = "*"
Port = 80
Path = "/"
MaxBufferSize = 10485760
AutoAuth = false

[SETTINGS]
LogLevel = 1
